stages:
  - test

test_python_app:
  stage: test
  image: python:3.10
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry install
    - source .venv/bin/activate
    - pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py
