stages:
  - test

test_linux:
  stage: test
  tags:
    - linux
  image: python:3.10
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry install
    - source .venv/bin/activate
    - pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py
  artifacts:
    paths:
      - dist/pyqt_helloworld

test_macos:
  stage: test
  tags:
    - saas-macos-medium-m1
  script:
    - brew install python@3.10
    - python -m pip install --upgrade pip
    - python -m pip install PyQt6==6.6.0 pyinstaller==6.2.0
    - pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py
  artifacts:
    paths:
      - dist/*

test_windows:
  stage: test
  tags:
    - windows
  before_script:
    # https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers/-/issues/13
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install python3 --version=3.10 --yes --force --no-progress
    - refreshenv
  script:
    - python -m pip install --upgrade pip
    - python -m pip install PyQt6==6.6.0 pyinstaller==6.2.0
    - pyinstaller --onefile --clean --windowed pyqt_helloworld\pyqt_helloworld.py
  artifacts:
    paths:
      - dist/pyqt_helloworld.exe
