# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.0.0

# https://circleci.com/docs/using-matrix-jobs/
executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: python:3.10
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02
  macos: # macos executor running Xcode
    macos:
      xcode: 14.2.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    parameters:
      platform:
        type: string
      python_version:
        type: string
    executor: << parameters.platform >>
    
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - when:
          condition:
            equal: [ linux, <<parameters.platform>> ]
          steps:
            - run:
                name: "Install python"
                command: |
                  sudo apt update
                  sudo apt-get install -y build-essential git
                  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
                  brew install python@<<parameters.python_version>>
                  ln -s /home/linuxbrew/.linuxbrew/bin/python<<parameters.python_version>> /home/linuxbrew/.linuxbrew/bin/python
                  echo 'export PATH=/home/linuxbrew/.linuxbrew/bin:"$PATH"' >> "$BASH_ENV"
      - when:
          condition:
            equal: [ macos, <<parameters.platform>> ]
          steps:
            - run:
                name: "Install python"
                command: |
                  brew install python@<<parameters.python_version>>
      - run:
          name: "Check python version"
          command: |
            python --version
            which python
      
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            python -m poetry install
      - run:
          name: "Build exe"
          command: |
            source .venv/bin/activate
            pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py
      - store_artifacts:
          path: dist


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          matrix:
            parameters:
              python_version: ["3.10"]
              platform: [docker, linux, macos]
