name: Test actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ptyhon-version: [3.10]
    
    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Set up Python
        uses: action/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install 
      
      - name: Build exec
        run: pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py