name: Test actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
        - Ubuntu-latest
        - Windows-latest
        python-version:
        - '3.10'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install 
      
      - name: Build exec (Linux)
        if: ${{ matrix.os == 'Ubuntu-latest' }}
        run: |
          source .venv/bin/activate
          pyinstaller --onefile --clean --windowed pyqt_helloworld/pyqt_helloworld.py
          
      - name: Build exec (Windows)
        if: ${{ matrix.os == 'Windows-latest' }}
        run: |
          .\.venv\Scripts\activate.ps1
          pyinstaller --onefile --clean --windowed pyqt_helloworld\pyqt_helloworld.py
